# Cloudflare Pages configuration for medical equipment management system
# This file is used for Cloudflare Pages deployment

# Note: For Cloudflare Pages, most configuration is done via the dashboard
# This file is kept minimal to avoid conflicts

# Project name (used for wrangler CLI operations)
name = "quan-ly-tbyt"

# Compatibility settings
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Node.js compatibility for Supabase client
node_compat = true
